export { default as AccountIcon } from "./account.svg";
export { default as AddIcon } from "./add.svg";
export { AddGoalIcon } from "./add-goal";
export { default as AngleDownIcon } from "./angle-down";
export { default as AngleUpIcon } from "./angle-up";
export { ArrowLeftIcon } from "./arrow-left";
export { default as BellIcon } from "./bell";
export { CalendarAltIcon } from "./calendar-alt";
export { default as CancelCircleBorderIcon } from "./cancel-circle";
export { CardIcon } from "./card";
export { CardSettingsIcon } from "./card-settings";
export { default as ChatIcon } from "./chat.svg";
export { CheckIcon } from "./check";
export { default as CheckmarkCircle } from "./checkmark-circle.svg";
export { ChevronRightIcon } from "./chevron-right";
export { default as ClearIcon } from "./clear.svg";
export { CloseIcon } from "./close-icon";
export { CopyIcon } from "./copy";
export { default as DisabledPlusIconCircle } from "./disabled-plus-circle.svg";
export { EditBordered } from "./edit-bordered";
export { default as ErrorIcon } from "./error.svg";
export { default as ErrorBlackIcon } from "./error-black.svg";
export { ErrorFilledCircleIcon } from "./error-filled-circle";
export { ErrorOutlineIcon } from "./error-outline";
export { FilledCircleTickIcon } from "./filled-circle-tick";
export { default as FilledRefresh } from "./filled-refresh.svg";
export { FreezeIcon } from "./freeze";
export { default as FriendIcon } from "./friend.svg";
export { default as FriendsIcon } from "./friends.svg";
export { default as GiftIcon } from "./gift.svg";
export { GlobeIcon } from "./globe";
export { default as HamburgerIcon } from "./hamburger.svg";
export { HideIcon } from "./hide";
export { default as InfoIcon } from "./info.svg";
export { InfoCircleIcon } from "./info-circle";
export { InfoFilledCircleIcon } from "./info-filled-circle";
export { default as InviteIcon } from "./invite.svg";
export { default as LargeFilledTickIcon } from "./large-filled-tick.svg";
export { default as Leaderboard } from "./leaderboard.svg";
export { LightningBoltIcon } from "./lightning-bolt";
export { default as LocationPinIcon } from "./location-pin.svg";
export { LockIcon } from "./lock";
export { default as ManageAccounts } from "./manage-accounts.svg";
export { MapMarkerIcon } from "./map-marker";
export { default as MinusIcon } from "./minus.svg";
export { default as NotificationIcon } from "./notification.svg";
export { default as PhoneIcon } from "./phone.svg";
export { PlusIcon } from "./plus";
export { default as PlusIconCircle } from "./plus-circle.svg";
export { default as PostcardIcon } from "./postcard.svg";
export { QuestionIcon } from "./question";
export { RecurringEventIcon } from "./recurring-event-icon";
export { default as ReferralIcon } from "./referral.svg";
export { default as ReferralsIcon } from "./referrals.svg";
export { ReportIcon } from "./report";
export { default as Rewards } from "./rewards.svg";
export { default as SearchIcon } from "./search.svg";
export { default as SettingsIcon } from "./settings.svg";
export { default as ShareCopyIcon } from "./share-copy.svg";
export { default as ShippingIcon } from "./shipping.svg";
export { ShowIcon } from "./show";
export { default as SplitIcon } from "./split.svg";
export { ThreeDotsIcon } from "./three-dots";
export { default as ThumbsDownIcon } from "./thumbs-down.svg";
export { default as ThumbsUpIcon } from "./thumbs-up.svg";
export { default as TickIcon } from "./tick.svg";
export { default as TickCircleIcon } from "./tick-circle";
export { default as TickCircleBorderIcon } from "./tick-circle-border";
export { default as TransferIcon } from "./transfer.svg";
export { default as TransferHorizontal } from "./transfer-horizontal.svg";
export { UserIcon } from "./user-icon";

export interface IconProps {
  color?: string;
  height?: number | string;
  width?: number | string;
}
