export { default as AccountIcon } from "./account.svg";
export { default as AddIcon } from "./add.svg";
export { BackIcon } from "./back-icon";
export { CalendarAltIcon } from "./calendar-alt";
export { default as CheckmarkCircle } from "./checkmark-circle.svg";
export { ChevronLeftIcon } from "./chevron-left";
export { ChevronRightIcon } from "./chevron-right";
export { default as ClearIcon } from "./clear.svg";
export { CloseIcon } from "./close-icon";
export { default as DisabledPlusIconCircle } from "./disabled-plus-circle.svg";
export { DownArrowIcon } from "./down-arrow-icon";
export { EditBordered } from "./edit-bordered";
export { default as ErrorIcon } from "./error.svg";
export { default as ErrorBlackIcon } from "./error-black.svg";
export { ErrorFilledCircleIcon } from "./error-filled-circle";
export { default as FriendIcon } from "./friend.svg";
export { default as FriendsIcon } from "./friends.svg";
export { default as GiftIcon } from "./gift.svg";
export { GlobeIcon } from "./globe";
export { default as HamburgerIcon } from "./hamburger.svg";
export { default as HideIcon } from "./hide.svg";
export { default as InfoIcon } from "./info.svg";
export { InfoCircleIcon } from "./info-circle";
export { InfoFilledCircleIcon } from "./info-filled-circle";
export { default as InviteIcon } from "./invite.svg";
export { LightningBoltIcon } from "./lightning-bolt";
export { default as LocationPinIcon } from "./location-pin.svg";
export { MapMarkerIcon } from "./map-marker";
export { default as MinusIcon } from "./minus.svg";
export { default as NotificationIcon } from "./notification.svg";
export { PlusIcon } from "./plus";
export { default as PlusIconCircle } from "./plus-circle.svg";
export { default as PostcardIcon } from "./postcard.svg";
export { QuestionIcon } from "./question";
export { RecurringEventIcon } from "./recurring-event-icon";
export { default as ReferralIcon } from "./referral.svg";
export { default as ReferralsIcon } from "./referrals.svg";
export { default as SettingsIcon } from "./settings.svg";
export { default as ShareCopyIcon } from "./share-copy.svg";
export { default as ShippingIcon } from "./shipping.svg";
export { default as ShowIcon } from "./show.svg";
export { default as SplitIcon } from "./split.svg";
export { default as TickIcon } from "./tick.svg";
export { default as TickCircleIcon } from "./tick-circle.svg";
export { default as TransferIcon } from "./transfer.svg";
export { UpArrowIcon } from "./up-arrow-icon";
export { UserIcon } from "./user-icon";

export interface IconProps {
  color?: string;
  height?: number | string;
  width?: number | string;
}
