import { ColorValue } from "react-native/types";

export { default as AccountIcon } from "./account";
export { default as AddBorderedIcon } from "./add-bordered";
export { default as AngleDownIcon } from "./angle-down";
export { default as AngleUpIcon } from "./angle-up";
export { default as AppleWalletIcon } from "./apple-wallet.svg";
export { ArrowForwardIcon } from "./arrow-forward";
export { ArrowLeftIcon } from "./arrow-left";
export { default as BellIcon } from "./bell";
export { CalendarAltIcon } from "./calendar-alt";
export { default as CancelCircleBorderIcon } from "./cancel-circle";
export { CardIcon } from "./card";
export { CardSettingsIcon } from "./card-settings";
export { default as ChatIcon } from "./chat";
export { CheckIcon } from "./check";
export { CheckIconBig } from "./check-big";
export { default as CheckCircle } from "./check-circle";
export { default as CheckmarkCircle } from "./checkmark-circle";
export { ChevronRightIcon } from "./chevron-right";
export { default as ClearIcon } from "./clear";
export { CloseIcon } from "./close-icon";
export { CopyIcon } from "./copy";
export { DeleteIcon } from "./delete-icon";
export { default as DisabledPlusIconCircle } from "./disabled-plus-circle";
export { EditIcon } from "./edit";
export { EditBordered } from "./edit-bordered";
export { default as ErrorIcon } from "./error";
export { default as ErrorBlackIcon } from "./error-black";
export { ErrorFilledCircleIcon } from "./error-filled-circle";
export { ErrorOutlineIcon } from "./error-outline";
export { FilledCircleTickIcon } from "./filled-circle-tick";
export { default as FilledRefresh } from "./filled-refresh";
export { FreezeIcon } from "./freeze";
export { default as FriendsIcon } from "./friends";
export { default as GiftIcon } from "./gift";
export { GlobeIcon } from "./globe";
export { default as HamburgerIcon } from "./hamburger";
export { HideIcon } from "./hide";
export { default as InfoIcon } from "./info";
export { InfoCircleIcon } from "./info-circle";
export { default as InfoFilledIcon } from "./info-filled";
export { InfoFilledCircleIcon } from "./info-filled-circle";
export { default as InviteIcon } from "./invite";
export { default as LargeFilledTickIcon } from "./large-filled-tick";
export { default as LeaderboardIcon } from "./leaderboard";
export { LightningBoltIcon } from "./lightning-bolt";
export { LocationPinIcon } from "./location-pin";
export { LockIcon } from "./lock";
export { default as ManageAccountsIcon } from "./manage-accounts";
export { MapMarkerIcon } from "./map-marker";
export { default as MinusIcon } from "./minus";
export { default as NotificationIcon } from "./notification";
export { default as PhoneIcon } from "./phone";
export { PlusIcon } from "./plus";
export { default as PlusIconCircle } from "./plus-circle";
export { default as PostcardIcon } from "./postcard";
export { QuestionIcon } from "./question";
export { RecurringEventIcon } from "./recurring-event-icon";
export { default as ReferralIcon } from "./referral";
export { default as ReferralsIcon } from "./referrals";
export { ReportIcon } from "./report";
export { default as RewardsIcon } from "./rewards";
export { default as SearchIcon } from "./search";
export { default as SettingsIcon } from "./settings";
export { default as ShippingIcon } from "./shipping";
export { ShowIcon } from "./show";
export { default as SplitIcon } from "./split";
export { default as SyncIcon } from "./sync";
export { ThreeDotsIcon } from "./three-dots";
export { ThreeDotsVerticalIcon } from "./three-dots-vertical";
export { default as ThumbsDownIcon } from "./thumbs-down";
export { default as ThumbsUpIcon } from "./thumbs-up";
export { default as TickIcon } from "./tick";
export { default as TickCircleIcon } from "./tick-circle";
export { default as TickCircleBorderIcon } from "./tick-circle-border";
export { default as TransferIcon } from "./transfer";
export { default as TransferHorizontalIcon } from "./transfer-horizontal";
export { default as TransferVertical } from "./transfer-vertical";
export { default as UserClockIcon } from "./user-clock";
export { UserIcon } from "./user-icon";
export { WithdrawIcon } from "./withdraw";

export interface IconProps {
  color?: ColorValue;
  height?: number | string;
  width?: number | string;
}
