export enum BiometricsInitiateDevicePayload {
  INITIAL_START = "INITIAL_START",
  INITIAL_DEVICE_ENROLL_SUCCESS = "INITIAL_DEVICE_ENROLL_SUCCESS",
  INITIAL_DEVICE_ENROLL_FAILURE = "INITIAL_DEVICE_ENROLL_FAILURE",
  NO_CHALLENGE = "NO_CHALLENGE",
  NO_SUCCESS_CREATING_SIG = "NO_SUCCESS_CREATING_SIG",
  SIG_CREATION_FAILURE = "SIG_CREATION_FAILURE",
  SIG_CREATION_SUCCESS = "SIG_CREATION_SUCCESS",
  KEY_CREATION_FAILURE = "KEY_CREATION_FAILURE",
  KEY_CREATION_SUCCESS = "KEY_CREATION_SUCCESS",
  FINISH_START = "FINISH_START",
  FINISH_SUCCESS = "FINISH_SUCCESS",
  FINISH_FAILURE = "FINISH_FAILURE",
}

export enum BiometryTypes {
  TouchID = "TouchID",
  FaceID = "FaceID",
  Biometrics = "Biometrics",
}
