export const WhatsNextMocks = [
  {
    ContentId: "string",
    ParentContentId: "string",
    ContentDataTypeId: "string",
    ContentCategoryId: "WhatsNext",
    ContentTag: "Top 10",
    ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
    Title: "string",
    ContentDescription: "string",
    Media: [
      {
        SourceFileName: "string",
        SourceFileDatatype: "Image",
        SourceFileURL: "string",
      },
    ],
    WhatsNextCategoryId: "1",
    WhatsNextCategory: "Sport",
    WhatsNextTypeId: "2",
    WhatsNextType: "Review",
    AuthorSocialMedia: [
      {
        Name: "string",
        Link: "string",
      },
    ],
    ChildrenContents: [
      {
        ContentId: "string",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Rihanna 2023",
        ContentDescription:
          "When Rihanna announced she'd be returning to performing at this year would be the best ever",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "3",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
      },
      {
        ContentId: "string",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Try out Ferrari F1-75 2023",
        ContentDescription: "When Rihanna announced she'd be returning to performing at this year yes",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
      },
      {
        ContentId: "string",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Rihanna 2023",
        ContentDescription: "When Rihanna announced she'd be returning to performing at this year yes",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
      },
      {
        ContentId: "string",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Try out Ferrari F1-75 2023",
        ContentDescription: "When Rihanna announced she'd be returning to performing at this year yes",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
      },
      {
        ContentId: "string",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Rihanna 2023",
        ContentDescription: "When Rihanna announced she'd be returning to performing at this year yes",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
      },
      {
        ContentId: "string",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Try out Ferrari F1-75 2023",
        ContentDescription: "When Rihanna announced she'd be returning to performing at this year yes",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
      },
      {
        ContentId: "string",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Rihanna 2023",
        ContentDescription: "When Rihanna announced she'd be returning to performing at this year yes",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
      },
      {
        ContentId: "string",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Try out Ferrari F1-75 2023",
        ContentDescription: "When Rihanna announced she'd be returning to performing at this year yes",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
      },
      {
        ContentId: "string",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Rihanna 2023",
        ContentDescription: "When Rihanna announced she'd be returning to performing at this year yes",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
      },
      {
        ContentId: "string",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Try out Ferrari F1-75 2023",
        ContentDescription: "When Rihanna announced she'd be returning to performing at this year yes",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
      },
    ],
  },
  {
    ContentId: "string",
    ParentContentId: "string",
    ContentDataTypeId: "string",
    ContentCategoryId: "WhatsNext",
    ContentTag: "explore",
    ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
    Title: "Backstage at the Imagine Dragons concert",
    ContentDescription: "So she was considering in her own mind (as well as she could, for the day making the best",
    Media: [
      {
        SourceFileName: "string",
        SourceFileDatatype: "Image",
        SourceFileURL: "string",
      },
    ],
    WhatsNextCategoryId: "1",
    WhatsNextCategory: "Sport",
    WhatsNextTypeId: "1",
    WhatsNextType: "Interview",
    AuthorSocialMedia: [
      {
        Name: "string",
        Link: "string",
      },
    ],
    ChildrenContents: [],
  },
  {
    ContentId: "string",
    ParentContentId: "string",
    ContentDataTypeId: "string",
    ContentCategoryId: "WhatsNext",
    ContentTag: "explore",
    ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
    Title: "What I’m excited about next month",
    ContentDescription:
      "A day like no other - spending one-on-one time with what some would call the pioneers of indie pop",
    Media: [
      {
        SourceFileName: "string",
        SourceFileDatatype: "Image",
        SourceFileURL: "string",
      },
    ],
    WhatsNextCategoryId: "1",
    WhatsNextCategory: "Fashion",
    WhatsNextTypeId: "2",
    WhatsNextType: "What's next for me",
    AuthorSocialMedia: [
      {
        Name: "string",
        Link: "string",
      },
    ],
    ChildrenContents: [],
  },
  {
    ContentId: "string",
    ParentContentId: "string",
    ContentDataTypeId: "string",
    ContentCategoryId: "WhatsNext",
    ContentTag: "explore",
    ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
    Title: "Alicia Keys - who is she today?",
    ContentDescription: "So she was considering in her own mind (as well as she could, for the day ma yes",
    Media: [
      {
        SourceFileName: "string",
        SourceFileDatatype: "Image",
        SourceFileURL: "string",
      },
    ],
    WhatsNextCategoryId: "1",
    WhatsNextCategory: "Film & Cinema",
    WhatsNextTypeId: "3",
    WhatsNextType: "Review",
    AuthorSocialMedia: [
      {
        Name: "string",
        Link: "string",
      },
    ],
    ChildrenContents: [],
  },
  {
    ContentId: "string",
    ParentContentId: "string",
    ContentDataTypeId: "string",
    ContentCategoryId: "WhatsNext",
    ContentTag: "explore",
    ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
    Title: "Why I loved ’The Avengers: Secret Wars’",
    ContentDescription: "So she was considering in her own mind (as well as she could, for the day ma yes",
    Media: [
      {
        SourceFileName: "string",
        SourceFileDatatype: "Image",
        SourceFileURL: "string",
      },
    ],
    WhatsNextCategoryId: "1",
    WhatsNextCategory: "Film & Cinema",
    WhatsNextTypeId: "4",
    WhatsNextType: "Behind the scenes",
    AuthorSocialMedia: [
      {
        Name: "string",
        Link: "string",
      },
    ],
    ChildrenContents: [],
  },
];

// export const WhatsNextMocks = [
//   {
//     ContentId: "string",
//     ParentContentId: "string",
//     ContentDataTypeId: "string",
//     ContentCategoryId: "string",
//     ContentTag: "topTen",
//     Version: "string",
//     VersionDate: "2023-04-19",
//     ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//     Title: "string",
//     SubTitle: "string",
//     ContentDescription: "string",
//     ProductCode: "string",
//     ProductTitle: "string",
//     Media: [
//       {
//         SourceFileName: "string",
//         SourceFileDatatype: "Video",
//         SourceFileURL: "string",
//       },
//     ],
//     WhatsNextCategory: "string",
//     WhatsNextType: "string",
//     AuthorName: "string",
//     AuthorAbout: "string",
//     RewardsLink: "string",
//     ReadDuration: 0,
//     AuthorSocialMedia: [
//       {
//         Name: "string",
//         Link: "string",
//       },
//     ],
//     EventDetails: {
//       EventDateTime: "2023-04-19T13:09:27.566Z",
//       OpeningHours: "string",
//       Location: "string",
//       Website: "string",
//       Price: 0,
//     },
//     ChildrenContents: [
//       {
//         ContentId: "string",
//         ParentContentId: "string",
//         ContentDataTypeId: "string",
//         ContentCategoryId: "string",
//         ContentTag: "Music",
//         Version: "string",
//         VersionDate: "2023-04-19",
//         ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//         Title: "Rihanna 2023",
//         SubTitle: "When Rihanna announced she'd be returning to performing at this year yes",
//         ContentDescription: "string",
//         ProductCode: "string",
//         ProductTitle: "string",
//         Media: [
//           {
//             SourceFileName: "string",
//             SourceFileDatatype: "Video",
//             SourceFileURL: "string",
//           },
//         ],
//         WhatsNextCategory: "string",
//         WhatsNextType: "string",
//         AuthorName: "string",
//         AuthorAbout: "string",
//         RewardsLink: "string",
//         ReadDuration: 0,
//         AuthorSocialMedia: [
//           {
//             Name: "string",
//             Link: "string",
//           },
//         ],
//         EventDetails: {
//           EventDateTime: "2023-04-19T13:09:27.566Z",
//           OpeningHours: "string",
//           Location: "string",
//           Website: "string",
//         },
//       },
//       {
//         ContentId: "string",
//         ParentContentId: "string",
//         ContentDataTypeId: "string",
//         ContentCategoryId: "string",
//         ContentTag: "Sport",
//         Version: "string",
//         VersionDate: "2023-04-19",
//         ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//         Title: "Try out Ferrari F1-75 2023",
//         SubTitle: "When Rihanna announced she'd be returning to performing at this year yes",
//         ContentDescription: "string",
//         ProductCode: "string",
//         ProductTitle: "string",
//         Media: [
//           {
//             SourceFileName: "string",
//             SourceFileDatatype: "Video",
//             SourceFileURL: "string",
//           },
//         ],
//         WhatsNextCategory: "string",
//         WhatsNextType: "string",
//         AuthorName: "string",
//         AuthorAbout: "string",
//         RewardsLink: "string",
//         ReadDuration: 0,
//         AuthorSocialMedia: [
//           {
//             Name: "string",
//             Link: "string",
//           },
//         ],
//         EventDetails: {
//           EventDateTime: "2023-04-19T13:09:27.566Z",
//           OpeningHours: "string",
//           Location: "string",
//           Website: "string",
//         },
//       },
//       {
//         ContentId: "string",
//         ParentContentId: "string",
//         ContentDataTypeId: "string",
//         ContentCategoryId: "string",
//         ContentTag: "Music",
//         Version: "string",
//         VersionDate: "2023-04-19",
//         ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//         Title: "Rihanna 2023",
//         SubTitle: "When Rihanna announced she'd be returning to performing at this year yes",
//         ContentDescription: "string",
//         ProductCode: "string",
//         ProductTitle: "string",
//         Media: [
//           {
//             SourceFileName: "string",
//             SourceFileDatatype: "Video",
//             SourceFileURL: "string",
//           },
//         ],
//         WhatsNextCategory: "string",
//         WhatsNextType: "string",
//         AuthorName: "string",
//         AuthorAbout: "string",
//         RewardsLink: "string",
//         ReadDuration: 0,
//         AuthorSocialMedia: [
//           {
//             Name: "string",
//             Link: "string",
//           },
//         ],
//         EventDetails: {
//           EventDateTime: "2023-04-19T13:09:27.566Z",
//           OpeningHours: "string",
//           Location: "string",
//           Website: "string",
//         },
//       },
//       {
//         ContentId: "string",
//         ParentContentId: "string",
//         ContentDataTypeId: "string",
//         ContentCategoryId: "string",
//         ContentTag: "Music",
//         Version: "string",
//         VersionDate: "2023-04-19",
//         ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//         Title: "Rihanna 2023",
//         SubTitle: "When Rihanna announced she'd be returning to performing at this year yes",
//         ContentDescription: "string",
//         ProductCode: "string",
//         ProductTitle: "string",
//         Media: [
//           {
//             SourceFileName: "string",
//             SourceFileDatatype: "Video",
//             SourceFileURL: "string",
//           },
//         ],
//         WhatsNextCategory: "string",
//         WhatsNextType: "string",
//         AuthorName: "string",
//         AuthorAbout: "string",
//         RewardsLink: "string",
//         ReadDuration: 0,
//         AuthorSocialMedia: [
//           {
//             Name: "string",
//             Link: "string",
//           },
//         ],
//         EventDetails: {
//           EventDateTime: "2023-04-19T13:09:27.566Z",
//           OpeningHours: "string",
//           Location: "string",
//           Website: "string",
//         },
//       },
//       {
//         ContentId: "string",
//         ParentContentId: "string",
//         ContentDataTypeId: "string",
//         ContentCategoryId: "string",
//         ContentTag: "Sport",
//         Version: "string",
//         VersionDate: "2023-04-19",
//         ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//         Title: "Try out Ferrari F1-75 2023",
//         SubTitle: "When Rihanna announced she'd be returning to performing at this year yes",
//         ContentDescription: "string",
//         ProductCode: "string",
//         ProductTitle: "string",
//         Media: [
//           {
//             SourceFileName: "string",
//             SourceFileDatatype: "Video",
//             SourceFileURL: "string",
//           },
//         ],
//         WhatsNextCategory: "string",
//         WhatsNextType: "string",
//         AuthorName: "string",
//         AuthorAbout: "string",
//         RewardsLink: "string",
//         ReadDuration: 0,
//         AuthorSocialMedia: [
//           {
//             Name: "string",
//             Link: "string",
//           },
//         ],
//         EventDetails: {
//           EventDateTime: "2023-04-19T13:09:27.566Z",
//           OpeningHours: "string",
//           Location: "string",
//           Website: "string",
//         },
//       },
//       {
//         ContentId: "string",
//         ParentContentId: "string",
//         ContentDataTypeId: "string",
//         ContentCategoryId: "string",
//         ContentTag: "Music",
//         Version: "string",
//         VersionDate: "2023-04-19",
//         ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//         Title: "Rihanna 2023",
//         SubTitle: "When Rihanna announced she'd be returning to performing at this year yes",
//         ContentDescription: "string",
//         ProductCode: "string",
//         ProductTitle: "string",
//         Media: [
//           {
//             SourceFileName: "string",
//             SourceFileDatatype: "Video",
//             SourceFileURL: "string",
//           },
//         ],
//         WhatsNextCategory: "string",
//         WhatsNextType: "string",
//         AuthorName: "string",
//         AuthorAbout: "string",
//         RewardsLink: "string",
//         ReadDuration: 0,
//         AuthorSocialMedia: [
//           {
//             Name: "string",
//             Link: "string",
//           },
//         ],
//         EventDetails: {
//           EventDateTime: "2023-04-19T13:09:27.566Z",
//           OpeningHours: "string",
//           Location: "string",
//           Website: "string",
//         },
//       },
//       {
//         ContentId: "string",
//         ParentContentId: "string",
//         ContentDataTypeId: "string",
//         ContentCategoryId: "string",
//         ContentTag: "Sport",
//         Version: "string",
//         VersionDate: "2023-04-19",
//         ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//         Title: "Try out Ferrari F1-75 2023",
//         SubTitle: "When Rihanna announced she'd be returning to performing at this year yes",
//         ContentDescription: "string",
//         ProductCode: "string",
//         ProductTitle: "string",
//         Media: [
//           {
//             SourceFileName: "string",
//             SourceFileDatatype: "Video",
//             SourceFileURL: "string",
//           },
//         ],
//         WhatsNextCategory: "string",
//         WhatsNextType: "string",
//         AuthorName: "string",
//         AuthorAbout: "string",
//         RewardsLink: "string",
//         ReadDuration: 0,
//         AuthorSocialMedia: [
//           {
//             Name: "string",
//             Link: "string",
//           },
//         ],
//         EventDetails: {
//           EventDateTime: "2023-04-19T13:09:27.566Z",
//           OpeningHours: "string",
//           Location: "string",
//           Website: "string",
//         },
//       },
//       {
//         ContentId: "string",
//         ParentContentId: "string",
//         ContentDataTypeId: "string",
//         ContentCategoryId: "string",
//         ContentTag: "Music",
//         Version: "string",
//         VersionDate: "2023-04-19",
//         ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//         Title: "Rihanna 2023",
//         SubTitle: "When Rihanna announced she'd be returning to performing at this year yes",
//         ContentDescription: "string",
//         ProductCode: "string",
//         ProductTitle: "string",
//         Media: [
//           {
//             SourceFileName: "string",
//             SourceFileDatatype: "Video",
//             SourceFileURL: "string",
//           },
//         ],
//         WhatsNextCategory: "string",
//         WhatsNextType: "string",
//         AuthorName: "string",
//         AuthorAbout: "string",
//         RewardsLink: "string",
//         ReadDuration: 0,
//         AuthorSocialMedia: [
//           {
//             Name: "string",
//             Link: "string",
//           },
//         ],
//         EventDetails: {
//           EventDateTime: "2023-04-19T13:09:27.566Z",
//           OpeningHours: "string",
//           Location: "string",
//           Website: "string",
//         },
//       },
//       {
//         ContentId: "string",
//         ParentContentId: "string",
//         ContentDataTypeId: "string",
//         ContentCategoryId: "string",
//         ContentTag: "Music",
//         Version: "string",
//         VersionDate: "2023-04-19",
//         ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//         Title: "Rihanna 2023",
//         SubTitle: "When Rihanna announced she'd be returning to performing at this year yes",
//         ContentDescription: "string",
//         ProductCode: "string",
//         ProductTitle: "string",
//         Media: [
//           {
//             SourceFileName: "string",
//             SourceFileDatatype: "Video",
//             SourceFileURL: "string",
//           },
//         ],
//         WhatsNextCategory: "string",
//         WhatsNextType: "string",
//         AuthorName: "string",
//         AuthorAbout: "string",
//         RewardsLink: "string",
//         ReadDuration: 0,
//         AuthorSocialMedia: [
//           {
//             Name: "string",
//             Link: "string",
//           },
//         ],
//         EventDetails: {
//           EventDateTime: "2023-04-19T13:09:27.566Z",
//           OpeningHours: "string",
//           Location: "string",
//           Website: "string",
//         },
//       },
//       {
//         ContentId: "string",
//         ParentContentId: "string",
//         ContentDataTypeId: "string",
//         ContentCategoryId: "string",
//         ContentTag: "Sport",
//         Version: "string",
//         VersionDate: "2023-04-19",
//         ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//         Title: "Try out Ferrari F1-75 2023",
//         SubTitle: "When Rihanna announced she'd be returning to performing at this year yes",
//         ContentDescription: "string",
//         ProductCode: "string",
//         ProductTitle: "string",
//         Media: [
//           {
//             SourceFileName: "string",
//             SourceFileDatatype: "Video",
//             SourceFileURL: "string",
//           },
//         ],
//         WhatsNextCategory: "string",
//         WhatsNextType: "string",
//         AuthorName: "string",
//         AuthorAbout: "string",
//         RewardsLink: "string",
//         ReadDuration: 0,
//         AuthorSocialMedia: [
//           {
//             Name: "string",
//             Link: "string",
//           },
//         ],
//         EventDetails: {
//           EventDateTime: "2023-04-19T13:09:27.566Z",
//           OpeningHours: "string",
//           Location: "string",
//           Website: "string",
//         },
//       },
//     ],
//   },
//   {
//     ContentId: "string",
//     ParentContentId: "string",
//     ContentDataTypeId: "string",
//     ContentCategoryId: "string",
//     ContentTag: "explore",
//     ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//     Title: "Backstage at the Imagine Dragons con yes",
//     SubTitle: "So she was considering in her own mind (as well as she could, for the day ma yes",
//     ContentDescription: "string",
//     ProductCode: "string",
//     ProductTitle: "string",
//     Media: [
//       {
//         SourceFileName: "string",
//         SourceFileDatatype: "Video",
//         SourceFileURL: "string",
//       },
//     ],
//     WhatsNextCategoryId: "1",
//     WhatsNextCategory: "Sport",
//     WhatsNextTypeId: "2",
//     WhatsNextType: "Behind the scenes",
//     AuthorName: "string",
//     AuthorAbout: "string",
//     RewardsLink: "string",
//     ReadDuration: 0,
//     AuthorSocialMedia: [
//       {
//         Name: "string",
//         Link: "string",
//       },
//     ],
//     EventDetails: {
//       EventDateTime: "2023-04-19T13:09:27.566Z",
//       OpeningHours: "string",
//       Location: "string",
//       Website: "string",
//       Price: 0,
//     },
//     ChildrenContents: [],
//   },
//   {
//     ContentId: "string",
//     ParentContentId: "string",
//     ContentDataTypeId: "string",
//     ContentCategoryId: "string",
//     ContentTag: "explore",
//     Version: "string",
//     VersionDate: "2023-04-19",
//     ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//     Title: "What I’m excited about next month",
//     SubTitle: "A day like no other - spending one-on-one time with what some would call the pioneers of indie pop",
//     ContentDescription: "string",
//     ProductCode: "string",
//     ProductTitle: "string",
//     Media: [
//       {
//         SourceFileName: "string",
//         SourceFileDatatype: "Video",
//         SourceFileURL: "string",
//       },
//     ],
//     WhatsNextCategory: "Fashion",
//     WhatsNextType: "What's next for me",
//     AuthorName: "string",
//     AuthorAbout: "string",
//     RewardsLink: "string",
//     ReadDuration: 0,
//     AuthorSocialMedia: [
//       {
//         Name: "string",
//         Link: "string",
//       },
//     ],
//     EventDetails: {
//       EventDateTime: "2023-04-19T13:09:27.566Z",
//       OpeningHours: "string",
//       Location: "string",
//       Website: "string",
//       Price: 0,
//     },
//     ChildrenContents: [],
//   },
//   {
//     ContentId: "string",
//     ParentContentId: "string",
//     ContentDataTypeId: "string",
//     ContentCategoryId: "string",
//     ContentTag: "explore",
//     Version: "string",
//     VersionDate: "2023-04-19",
//     ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//     Title: "Alicia Keys - who is she today?",
//     SubTitle: "So she was considering in her own mind (as well as she could, for the day ma yes",
//     ContentDescription: "string",
//     ProductCode: "string",
//     ProductTitle: "string",
//     Media: [
//       {
//         SourceFileName: "string",
//         SourceFileDatatype: "Video",
//         SourceFileURL: "string",
//       },
//     ],
//     WhatsNextCategory: "Film & Cinema",
//     WhatsNextType: "Review",
//     AuthorName: "string",
//     AuthorAbout: "string",
//     RewardsLink: "string",
//     ReadDuration: 0,
//     AuthorSocialMedia: [
//       {
//         Name: "string",
//         Link: "string",
//       },
//     ],
//     EventDetails: {
//       EventDateTime: "2023-04-19T13:09:27.566Z",
//       OpeningHours: "string",
//       Location: "string",
//       Website: "string",
//       Price: 0,
//     },
//     ChildrenContents: [],
//   },
//   {
//     ContentId: "string",
//     ParentContentId: "string",
//     ContentDataTypeId: "string",
//     ContentCategoryId: "string",
//     ContentTag: "explore",
//     Version: "string",
//     VersionDate: "2023-04-19",
//     ContentPublishDateTime: "2023-04-19T13:09:27.566Z",
//     Title: "Why I loved ’The Avengers: Secret Wars’",
//     SubTitle: "So she was considering in her own mind (as well as she could, for the day ma yes",
//     ContentDescription: "string",
//     ProductCode: "string",
//     ProductTitle: "string",
//     Media: [
//       {
//         SourceFileName: "string",
//         SourceFileDatatype: "Video",
//         SourceFileURL: "string",
//       },
//     ],
//     WhatsNextCategory: "Gaming & Technology",
//     WhatsNextType: "Interview",
//     AuthorName: "string",
//     AuthorAbout: "string",
//     RewardsLink: "string",
//     ReadDuration: 0,
//     AuthorSocialMedia: [
//       {
//         Name: "string",
//         Link: "string",
//       },
//     ],
//     EventDetails: {
//       EventDateTime: "2023-04-19T13:09:27.566Z",
//       OpeningHours: "string",
//       Location: "string",
//       Website: "string",
//       Price: 0,
//     },
//     ChildrenContents: [],
//   },
// ];
