export const WhatsNextMocks = [
  {
    ContentId: "193847",
    ParentContentId: "string",
    ContentDataTypeId: "string",
    ContentCategoryId: "WhatsNext",
    ContentTag: "Top 10",
    ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
    Title: "Lorem Ipsum",
    SubTitle:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    ContentDescription: "string",
    Media: [
      {
        SourceFileName: "string",
        SourceFileDatatype: "Video",
        SourceFileURL: "string",
      },
    ],
    WhatsNextCategoryId: "1",
    WhatsNextCategory: "Sport",
    WhatsNextTypeId: "2",
    WhatsNextType: "Review",
    AuthorName: "string",
    AuthorAbout: "string",
    AuthorSocialMedia: {
      Name: "string",
      Link: "string",
    },
    ChildrenContents: [
      {
        ContentId: "1",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Rihanna 2023",
        SubTitle: "string",
        ContentDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "3",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
        EventDetails: {
          OpeningHours: "20:00 - 22:00",
          Location: "Boulevard Riyadh City 13, Riyadh, KSA",
          Price: "395",
        },
      },
      {
        ContentId: "2",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Try out Ferrari F1-75 2023",
        SubTitle: "string",
        ContentDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
        EventDetails: {
          OpeningHours: "20:00 - 22:00",
          Location: "Boulevard Riyadh City 13, Riyadh, KSA",
          Price: "395",
        },
      },
      {
        ContentId: "3",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Rihanna 2023",
        SubTitle: "string",
        ContentDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
        EventDetails: {
          OpeningHours: "20:00 - 22:00",
          Location: "Boulevard Riyadh City 13, Riyadh, KSA",
          Price: "395",
        },
      },
      {
        ContentId: "4",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Try out Ferrari F1-75 2023",
        SubTitle: "string",
        ContentDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
        EventDetails: {
          OpeningHours: "20:00 - 22:00",
          Location: "Boulevard Riyadh City 13, Riyadh, KSA",
          Price: "395",
        },
      },
      {
        ContentId: "5",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Rihanna 2023",
        SubTitle: "string",
        ContentDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
        EventDetails: {
          OpeningHours: "20:00 - 22:00",
          Location: "Boulevard Riyadh City 13, Riyadh, KSA",
          Price: "395",
        },
      },
      {
        ContentId: "6",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Try out Ferrari F1-75 2023",
        SubTitle: "string",
        ContentDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
        EventDetails: {
          OpeningHours: "20:00 - 22:00",
          Location: "Boulevard Riyadh City 13, Riyadh, KSA",
          Price: "395",
        },
      },
      {
        ContentId: "7",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Rihanna 2023",
        SubTitle: "string",
        ContentDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
        EventDetails: {
          OpeningHours: "20:00 - 22:00",
          Location: "Boulevard Riyadh City 13, Riyadh, KSA",
          Price: "395",
        },
      },
      {
        ContentId: "8",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Try out Ferrari F1-75 2023",
        SubTitle: "string",
        ContentDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
        EventDetails: {
          OpeningHours: "20:00 - 22:00",
          Location: "Boulevard Riyadh City 13, Riyadh, KSA",
          Price: "395",
        },
      },
      {
        ContentId: "9",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Rihanna 2023",
        SubTitle: "string",
        ContentDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
        EventDetails: {
          OpeningHours: "20:00 - 22:00",
          Location: "Boulevard Riyadh City 13, Riyadh, KSA",
          Price: "395",
        },
      },
      {
        ContentId: "10",
        ParentContentId: "string",
        ContentDataTypeId: "string",
        ContentCategoryId: "WhatsNext",
        ContentTag: "string",
        ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
        Title: "Try out Ferrari F1-75 2023",
        SubTitle: "string",
        ContentDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        Media: [
          {
            SourceFileName: "string",
            SourceFileDatatype: "Video",
            SourceFileURL: "string",
          },
        ],
        WhatsNextCategoryId: "1",
        WhatsNextCategory: "Sport",
        WhatsNextTypeId: "2",
        WhatsNextType: "Review",
        AuthorSocialMedia: [
          {
            Name: "string",
            Link: "string",
          },
        ],
        EventDetails: {
          OpeningHours: "20:00 - 22:00",
          Location: "Boulevard Riyadh City 13, Riyadh, KSA",
          Price: "395",
        },
      },
    ],
  },
  {
    ContentId: "123567",
    ParentContentId: "string",
    ContentDataTypeId: "string",
    ContentCategoryId: "WhatsNext",
    ContentTag: "explore",
    ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
    Title: "Backstage at the Imagine Dragons concert",
    SubTitle: '"And what is the use of a book," thought Alice, "without pictures or conversations?"',
    ContentDescription:
      "<b>Alice was beginning to get very tired </b></br><br>So she was considering in her own mind whether the pleasure of making a daisy chain would be worth the trouble of getting up and picking the daisies.<br><br>So she was considering in her own mind whether the pleasure of making a daisy chain would be worth the trouble of getting up and picking the daisies. Once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, 'and what is the use of a book,' thought Alice, 'without pictures or conversations?'<br><br><b>Alice was beginning to get very tired </b></br><br>So she was considering in her own mind whether the pleasure of making a daisy chain would be worth the trouble of getting up and picking the daisies.<br><br>So she was considering in her own mind whether the pleasure of making a daisy chain would be worth the trouble of getting up and picking the daisies. Once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, 'and what is the use of a book,' thought Alice, 'without pictures or conversations?'",
    Media: [
      {
        SourceFileName: "string",
        SourceFileDatatype: "Video",
        SourceFileURL: "https://www.google.com",
      },
    ],
    WhatsNextCategoryId: "1",
    WhatsNextCategory: "Sport",
    WhatsNextTypeId: "1",
    WhatsNextType: "Interview",
    AuthorName: "string",
    AuthorAbout:
      "Manal writes on life, travel, culture, psychology, literature and socio-politics. Top Writer in Music.",
    AuthorSocialMedia: {
      Name: "@socialmediahandle",
      Link: "https://www.google.com",
    },
    EventDetails: {
      EventDateTime: "2023-05-03T11:31:43.032Z",
      OpeningHours: "08:00 - 22:00",
      Location: "Boulevard Riyadh City 13, Riyadh, KSA",
      Website: "https://www.google.com",
      Price: 300,
    },
    ChildrenContents: [],
  },
  {
    ContentId: "123789",
    ParentContentId: "string",
    ContentDataTypeId: "string",
    ContentCategoryId: "WhatsNext",
    ContentTag: "explore",
    ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
    Title: "What I’m excited about next month",
    SubTitle: "string",
    ContentDescription:
      "A day like no other - spending one-on-one time with what some would call the pioneers of indie pop",
    Media: [
      {
        SourceFileName: "string",
        SourceFileDatatype: "Video",
        SourceFileURL: "string",
      },
    ],
    WhatsNextCategoryId: "1",
    WhatsNextCategory: "Fashion",
    WhatsNextTypeId: "2",
    WhatsNextType: "What's next for me",
    AuthorName: "string",
    AuthorAbout: "string",
    AuthorSocialMedia: {
      Name: "string",
      Link: "string",
    },
    ChildrenContents: [],
  },
  {
    ContentId: "123123",
    ParentContentId: "string",
    ContentDataTypeId: "string",
    ContentCategoryId: "WhatsNext",
    ContentTag: "explore",
    ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
    Title: "Alicia Keys - who is she today?",
    SubTitle: "string",
    ContentDescription: "So she was considering in her own mind (as well as she could, for the day ma yes",
    Media: [
      {
        SourceFileName: "string",
        SourceFileDatatype: "Video",
        SourceFileURL: "string",
      },
    ],
    WhatsNextCategoryId: "1",
    WhatsNextCategory: "Film & Cinema",
    WhatsNextTypeId: "3",
    WhatsNextType: "Review",
    AuthorName: "string",
    AuthorAbout: "string",
    AuthorSocialMedia: {
      Name: "string",
      Link: "string",
    },
    ChildrenContents: [],
  },
  {
    ContentId: "123890",
    ParentContentId: "string",
    ContentDataTypeId: "string",
    ContentCategoryId: "WhatsNext",
    ContentTag: "explore",
    ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
    Title: "Why I loved ’The Avengers: Secret Wars’",
    SubTitle: "string",
    ContentDescription: "So she was considering in her own mind (as well as she could, for the day ma yes",
    Media: [
      {
        SourceFileName: "string",
        SourceFileDatatype: "Video",
        SourceFileURL: "string",
      },
    ],
    WhatsNextCategoryId: "1",
    WhatsNextCategory: "Film & Cinema",
    WhatsNextTypeId: "4",
    WhatsNextType: "Behind the scenes",
    AuthorName: "string",
    AuthorAbout: "string",
    AuthorSocialMedia: {
      Name: "string",
      Link: "string",
    },
    ChildrenContents: [],
  },
  {
    WhatsNextCategories: ["Film & Cinema", "Music", "Fashion", "Restaurants & Cafes", "Sport", "Gaming & Technology"],
    WhatsNextTypes: ["Review", "Interviews", "Behind the scenes", "What's next for me"],
  },
  {
    ContentId: "123476",
    ParentContentId: "string",
    ContentDataTypeId: "string",
    ContentCategoryId: "WhatsNext",
    ContentTag: "explore",
    ContentPublishDateTime: "2023-04-19T10:30:39.581Z",
    Title: "Alicia Keys - who is she today?",
    SubTitle: "string",
    ContentDescription: "So she was considering in her own mind (as well as she could, for the day ma yes",
    Media: [
      {
        SourceFileName: "string",
        SourceFileDatatype: "Video",
        SourceFileURL: "string",
      },
    ],
    WhatsNextCategoryId: "1",
    WhatsNextCategory: "Sport",
    WhatsNextTypeId: "3",
    WhatsNextType: "Interview",
    AuthorName: "string",
    AuthorAbout: "string",
    AuthorSocialMedia: {
      Name: "string",
      Link: "string",
    },
    ChildrenContents: [],
  },
];
